'use client'

import { useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { MessageCircle } from 'lucide-react'
import { getSupabaseBrowser } from '@/lib/supabase/client'
import { PLATFORM_NAME, TAGLINE, SHORT_DISCLAIMER } from '@/lib/constants'

type Step = 'phone' | 'otp'

// Flip to true once the PaisaJag WABA is verified and the Supabase
// phone provider + WhatsApp delivery hook are configured.
const WHATSAPP_LOGIN_ENABLED = false

export default function LoginPage() {
  const router = useRouter()
  const supabase = getSupabaseBrowser()
  const [step, setStep] = useState<Step>('phone')
  const [phone, setPhone] = useState('')
  const [otp, setOtp] = useState('')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const phoneValid = /^[6-9]\d{9}$/.test(phone)

  async function sendOtp() {
    setError(null)
    if (!phoneValid) {
      setError('Please enter a 10-digit Indian mobile number.')
      return
    }
    if (!supabase) {
      // Preview mode — backend not wired yet
      setStep('otp')
      return
    }
    setBusy(true)
    // OTP is generated by Supabase and delivered via WhatsApp
    // through the custom SMS hook (see TECH_STACK.md)
    const { error } = await supabase.auth.signInWithOtp({
      phone: `+91${phone}`,
    })
    setBusy(false)
    if (error) {
      setError('Something went wrong on our end. Please try again in a moment.')
      return
    }
    setStep('otp')
  }

  async function verifyOtp() {
    setError(null)
    if (otp.length !== 6) {
      setError('The code has 6 digits.')
      return
    }
    if (!supabase) {
      router.push('/onboarding')
      return
    }
    setBusy(true)
    const { data, error } = await supabase.auth.verifyOtp({
      phone: `+91${phone}`,
      token: otp,
      type: 'sms', // stays 'sms' even though delivered via WhatsApp
    })
    setBusy(false)
    if (error || !data.session) {
      setError('That code didn’t match. Please check and try again.')
      return
    }
    const { data: profile } = await supabase
      .from('profiles')
      .select('dna_complete')
      .eq('user_id', data.session.user.id)
      .maybeSingle()
    if (!profile) router.push('/onboarding')
    else if (!profile.dna_complete) router.push('/onboarding')
    else router.push('/dashboard?check_in=true')
  }

  async function googleSignIn() {
    setError(null)
    if (!supabase) {
      router.push('/onboarding')
      return
    }
    await supabase.auth.signInWithOAuth({
      provider: 'google',
      options: { redirectTo: `${window.location.origin}/auth/callback` },
    })
  }

  return (
    <main className="flex min-h-screen flex-col bg-amber-50 px-6 py-12">
      <div className="mx-auto w-full max-w-sm flex-1">
        <div className="text-center">
          <Link href="/" className="text-2xl font-medium text-amber-600">
            {PLATFORM_NAME}
          </Link>
          <p className="mt-1 text-sm text-amber-800">{TAGLINE}</p>
        </div>

        <div className="card mt-10 space-y-5">
          {step === 'phone' ? (
            <>
              <div>
                <h1 className="text-lg font-medium text-gray-900">Welcome</h1>
                <p className="mt-1 text-sm text-gray-600">
                  Sign in with Google to get started. No passwords, ever.
                </p>
              </div>
              <button className="btn-primary" onClick={googleSignIn}>
                Continue with Google
              </button>
              <div className="flex items-center gap-3">
                <span className="h-px flex-1 bg-gray-200" />
                <span className="text-xs text-gray-400">or</span>
                <span className="h-px flex-1 bg-gray-200" />
              </div>
              {WHATSAPP_LOGIN_ENABLED ? (
                <>
                  <div>
                    <label htmlFor="phone" className="label">
                      Mobile number
                    </label>
                    <div className="flex gap-2">
                      <span className="flex items-center rounded-md border border-gray-200 bg-gray-50 px-3 text-gray-600">
                        +91
                      </span>
                      <input
                        id="phone"
                        type="tel"
                        inputMode="numeric"
                        autoComplete="tel-national"
                        maxLength={10}
                        className="input"
                        placeholder="98765 43210"
                        value={phone}
                        onChange={(e) =>
                          setPhone(e.target.value.replace(/\D/g, ''))
                        }
                      />
                    </div>
                  </div>
                  <button
                    className="btn-primary flex items-center justify-center gap-2"
                    onClick={sendOtp}
                    disabled={busy}
                  >
                    <MessageCircle size={18} aria-hidden />
                    {busy ? 'Sending…' : 'Send code on WhatsApp'}
                  </button>
                </>
              ) : (
                <button
                  className="btn-ghost flex items-center justify-center gap-2 opacity-60"
                  disabled
                >
                  <MessageCircle size={18} aria-hidden />
                  WhatsApp login — coming soon
                </button>
              )}
            </>
          ) : (
            <>
              <div>
                <h1 className="text-lg font-medium text-gray-900">
                  Check your WhatsApp
                </h1>
                <p className="mt-1 text-sm text-gray-600">
                  We sent a 6-digit code to +91 {phone}. It’s valid for 10
                  minutes.
                </p>
              </div>
              <div>
                <label htmlFor="otp" className="label">
                  Verification code
                </label>
                <input
                  id="otp"
                  type="text"
                  inputMode="numeric"
                  autoComplete="one-time-code"
                  maxLength={6}
                  className="input text-center text-xl tracking-[0.5em]"
                  value={otp}
                  onChange={(e) => setOtp(e.target.value.replace(/\D/g, ''))}
                />
              </div>
              <button
                className="btn-primary"
                onClick={verifyOtp}
                disabled={busy}
              >
                {busy ? 'Verifying…' : 'Verify and continue'}
              </button>
              <button
                className="w-full text-center text-sm text-amber-800 underline"
                onClick={() => {
                  setOtp('')
                  setStep('phone')
                }}
              >
                Use a different number
              </button>
            </>
          )}

          {error && (
            <p role="alert" className="text-sm text-red-600">
              {error}
            </p>
          )}
        </div>

        <p className="mt-6 text-center text-xs text-gray-400">
          By continuing you agree to our{' '}
          <Link href="/terms" className="underline">
            Terms
          </Link>{' '}
          and{' '}
          <Link href="/privacy" className="underline">
            Privacy Policy
          </Link>
          .
        </p>
      </div>
      <p className="mt-8 text-center text-xs text-gray-400">
        {SHORT_DISCLAIMER}
      </p>
    </main>
  )
}
